version: '3.1'

services:

  database:
    image: mongo
    ports:
    - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: develop
      MONGO_INITDB_ROOT_PASSWORD: develop