http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  hello:
    host: localhost
    paths:
      - '/hello'
      - '/hello/*'
  auth:
    host: localhost
    paths:
      - '/auth'
      - '/auth/*'
serviceEndpoints:
  hello-service:
    url: 'http://localhost:3080'
  auth-service:
    url: 'http://localhost:5001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: say-hello
    apiEndpoints:
      - hello
    policies:
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: hello-service
              changeOrigin: true
  - name: auth
    apiEndpoints:
      - auth
    policies:
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: auth-service
              changeOrigin: true
